name: build base
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - docker/**
jobs:
  push:
    name: "base:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oses:
          - java

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "nyxalis"
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.oses }}
          file: ./docker/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/nyxalis/base-env:${{ matrix.oses }}
